#servidor
server:
  port: 8081
  servlet:
    context-path: /post

spring:

  #banco de dados
  datasource:
    url: jdbc:h2:mem:post

  jpa:
    database: H2
    show-sql: true
    properties:
      format_sql: true
  flyway:
    enabled: true

